### ISSUE TITLE
No apparent SRAM patching in app

### ISSUE THREAD

**Issue by Dimensional** [Mte90/GBAATM-Rebirth#14]
It is known that in the original GBAATM, it had an option to SRAM patch a game, for older flash carts that didn't handle other types. And we know that GBARunner2 only can handle SRAM saves, with the ability to patch some games automatically, but a few games, namely Golden Sun The Lost Age, needs it done manually.

Upon looking around, I'm unable to find anything within the code or comments stating that the new Rebirth version has SRAM patching. Will this be enabled in the near future as an optional feature, for those who use things like GBARunner2?

**Comment by Mte90** [comment]
The original code of GBAATM is available so you can check https://github.com/Mte90/GBAATM-Rebirth/releases/tag/original

The code of this tool is based on this, I didn't remove anything about feature except the slowmo feature.
Looking on the tool there is any trace of SRAM options.

**Comment by Dimensional** [comment]
I did a search through the repo for anything saying "sram", but never found it. If it was in the original code, it wasn't spelled out as such, either internally or as a gui option.

**Comment by Mte90** [comment]
Yes I don't remember anything like that and looking on the windows version there is no option for that.

So maybe there wasn't any flag and it was already in the assembly code that is injected.  
In my tests that feature wasn't avalaible, are you sure that GBAATM original version has SRAM patcher?

Looking on internet I can't find anything about it.

**Comment by Dimensional** [comment]
Yes. And it's my mistake. I was looking at the GBARunner2 github page, and I realize I misread GBATA as GBAATM. Here's the snippet that I misread. 

- Games generally don't need to be SRAM patched unless stated in the compatibility list (see below). If it is needed, you can use [gbata](http://www.no-intro.org/gbadat/tools/gbata7a-en.zip).

I spent hours looking for the wrong thing because of misreading one sentence.
https://no-intro.org/tools.htm

**Comment by Mte90** [comment]
No problem :-)
