### ISSUE TITLE
[BUG] GBAATM-Rebirth crashes when I try to patch rom

### ISSUE THREAD

**Issue by bloggingninja** [Mte90/GBAATM-Rebirth#17]
When I follow steps found online, the app crashes and disappears when I click "Patch Game"

OS: Windows 10 x64
GBAATM-Rebirth version: Pre-1.0.0 Alpha2
Games: multiple, but mostly tested with dumps from my pokemon games.

**Comment by Mte90** [comment]
Hi, this report is not helpful to debug the issue are you facing.
I need to know what rom, what cheat are you using and so on...
